### ISSUE TITLE
Is this project Open Source?

### ISSUE THREAD

**Issue by abetusk** [bleeptrack/fr0zen-system-laser#1]
From your [video](https://www.youtube.com/watch?v=-WHORPKPZP4) you say:

> ... as always it's an open source project and you can use the generated images for everything you want ...

As of this writing, this project is "closed source" (at least here in the US) since there is no indication about what license is that the project falls under.

"Open Source" has a generally accepted meaning of being able to re-use the digital artifacts for commercial purposes. The [OSI](https://opensource.org/osd) and Wikipedia's entry on [open-source licensing](https://en.wikipedia.org/wiki/Open-source_license) both articulate that commercial re-use is a (generally accepted) requirement of an "open source" license.

Was the intent to make this project libre/free/open source? 

If so, could you indicate the license, either by providing a `LICENSE` file with the appropriate license or by putting a license preamble in each of the source files (preferably both).

If not, it might be good to clarify what the restrictions are to avoid confusion.

**Comment by bleeptrack** [comment]
Hey Abe,
thanks so much for noticing! I added a license file and a remark into the readme with commit fdf9103ab06277261195564c39f9c2e2568f017a :) Hope you enjoy fr0zen system!
